### ISSUE TITLE
Error when uploading source maps from EAS build

### ISSUE THREAD

**Issue by ghost** [bugsnag/bugsnag-expo#62] opened 2022-09-21 21:55 UTC
### Describe the bug

After submitting a built to EAS:

1. Android built successfully and source maps were uploaded.
2. iOS failed with the following error:

```
› Executing Flowchase » Upload source maps to Bugsnag
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution Upload\ source\ maps\ to\ Bugsnag /Users/expo/Library/Developer/Xcode/DerivedData/Flowchase-dqtytsgkfadtwteridyhlzhrlmyt/Build/Intermediates.noindex/ArchiveIntermediates/Flowchase/IntermediateBuildFilesPath/Flowchase.build/Release-iphoneos/Flowchase.build/Script-026EE93FE26B4D48B5B4D384.sh (in target 'Flowchase' from project 'Flowchase')
```

To be clear: this *causes* an iOS build to fail.

Let me know if there's any extra info I can provide, I'd like to help :)

### Steps to reproduce

???

### Environment

* Bugsnag version: 46.0.0
* Expo SDK version (e.g. SDK 44): 46.0.9
* Device (e.g. iphonex): N/A
* `@bugsnag/plugin-expo-eas-sourcemaps`: 46.0.0

<details><summary>Error messages:</summary>

```
› Executing Flowchase » Upload source maps to Bugsnag
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution Upload\ source\ maps\ to\ Bugsnag /Users/expo/Library/Developer/Xcode/DerivedData/Flowchase-dqtytsgkfadtwteridyhlzhrlmyt/Build/Intermediates.noindex/ArchiveIntermediates/Flowchase/IntermediateBuildFilesPath/Flowchase.build/Release-iphoneos/Flowchase.build/Script-026EE93FE26B4D48B5B4D384.sh (in target 'Flowchase' from project 'Flowchase')
```
</details>

**Comment by gingerbenw** [comment] 2022-09-22 13:43
Hi @filipecatraia! Are you using a monorepo here, or a standalone repo?

**Comment by ghost** [comment] 2022-09-23 18:01
@gingerbenw Standalone! I saw the other issue about monorepos :) I ended up removing sourcemaps, otherwise I couldn't build on iOS.

**Comment by renatoniro** [comment] 2022-09-27 19:16
👋 Hey there! - commenting to follow along with this thread as I also seem to be seeing the same behaviour with iOS builds failing in EAS at the final step where bugsnag sourcemaps are uploaded (PhaseScriptExecution fails), thus holding up app-store releases. My project is also not a monorepo. 

### Environment
Bugsnag version: `45.0.0`
Expo SDK version (e.g. SDK 44): `45.0.0`
@bugsnag/plugin-expo-eas-sourcemaps: `45.1.0` (I have also tried with the latest `46.0.1`)

**Comment by nickdowell** [comment] 2022-09-28 14:18
We have not (yet) been able to reproduce this build issue.

If you're willing and able to reproduce it in a [local build](https://docs.expo.dev/build-reference/local-builds/) we will hopefully be able to get more logs and determine the cause. The following commands replicate EAS's build process locally:

```sh
export EAS_LOCAL_BUILD_ARTIFACTS_DIR=/tmp/eas-build
export EAS_LOCAL_BUILD_SKIP_CLEANUP=1
eas build --platform ios --local
```

Opening the Xcode project left in `$EAS_LOCAL_BUILD_ARTIFACTS_DIR` and building it directly in Xcode should provide the more verbose logs that we need. Thanks!

**Comment by ghost** [comment] 2022-09-28 14:24
Sadly, the last time I tried to build locally, I ended up in a 4-day quest down the rabbit hole onto the land of madness. If we knew the build IDs, is there any chance you can convince Expo to give us better logs and/or a copy of the build artifacts?

**Comment by gingerbenw** [comment] 2022-09-29 15:50
Hi @filipecatraia, you should be able to download the full Xcode logs by expanding the `> Xcode logs` build stage and hitting "Download".

If you could write to us at support@bugsnag.com with your build ID, we can pass that over to the Expo team for further investigation.

**Comment by ghost** [comment] 2022-09-30 09:24
Hey @gingerbenw, these had the issue we're describing here:

- `e7d27602-7515-4ea4-af5c-2f7256e535dd`
- `47af6b96-f5da-4cda-95b3-584e1eb31be7`

Good luck with Expo!

**Comment by kennethlynne** [comment] 2022-11-08 15:12
I'm very confused how to get source maps. The expo docs are very confusing on the topic (see https://github.com/expo/expo/issues/19934) and the bugsnag docs say that we only get source maps for `release builds` whatever that means. However the CLI supports dumping source maps already (see https://github.com/expo/eas-cli/commit/7ebb547fd9e8ab2ef2d7e85c40a34067352fcc3a#), so how can we get source maps for anything we want? 

Sentry makes this seemingly super easy and configurable (see https://docs.expo.dev/guides/using-sentry) so I hope bugsnag can adopt a similar approach and help out on the bugsnag expo docs

**Comment by johnkiely1** [comment] 2023-01-17 17:18
Apologies for the delays on this, we did manage to get the following from expo 
```

Error: SOURCE_MAP /var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T//bb15bffadd4744905fca39ed5195ffdb-main.jsbundle.map could not be found.
Ensure the --sourcemap-output option is passed to the react-native bundle command.
Command PhaseScriptExecution failed with a nonzero exit code
```
Unfortunately it's difficult for us to tell or investigate exactly why this file wouldn't be found other than suggesting that sourcemap wasn’t being generated or wasn’t in the correct location. We have tried to reproduce what you are seeing but we have not been able to. Have you managed to get any further or are you still seeing the same issue?

**Comment by johnkiely1** [comment] 2023-02-17 14:04
Going to close this out at there is not a lot more we can do at this point, happy to reopen if you have any additional information you can share.

**Comment by joaquin03** [comment] 2023-12-06 17:13
Is there any news on this? I'm having the same issue.

**Comment by clr182** [comment] 2023-12-07 10:37
Hi @joaquin03 
Unfortunately we do not have an update on this issue. However, as per the above suggestions if you are able to reproduce this issue in a local build then we should be able to get more logs and determine the cause.

**Closed as completed** 2024-02-23 11:59 UTC
